INSERT INTO JDBC_POLL (POLL_DATA, STATUS) VALUES('foo1', 0);
INSERT INTO JDBC_POLL (POLL_DATA, STATUS) VALUES('foo2', 0);
INSERT INTO JDBC_POLL (POLL_DATA, STATUS) VALUES('foo3', 0);
INSERT INTO JDBC_POLL (POLL_DATA, STATUS) VALUES('foo4', 0);
