--DROP TABLE IF EXISTS QUEUED;
--DROP TABLE IF EXISTS LOCK_STATUS;
--DROP TABLE IF EXISTS LASTPOLL;

CREATE TABLE IF NOT EXISTS QUEUED (
	 ID BIGINT 		IDENTITY NOT NULL PRIMARY KEY
	,ENTITY_ID		VARCHAR(128) NOT NULL
	,PROCESS_ID		VARCHAR(128) NOT NULL
	,TS				TIMESTAMP
	,MESSAGE		BLOB
);

create sequence IF NOT EXISTS lock_status_sequence;

CREATE TABLE IF NOT EXISTS LOCK_STATUS (
	 ID BIGINT IDENTITY NOT NULL PRIMARY KEY
	,ENTITY_ID		VARCHAR(128) NOT NULL
	,DISPATCHER_ID	VARCHAR(128) NOT NULL
	,GLOBAL_TX		VARCHAR(128)
	,PROCESS_ID		VARCHAR(128) NOT NULL
	,DEDUP_KEY		VARCHAR(128) 
	,STATUS			INTEGER		 NOT NULL
	,TS				TIMESTAMP 
);

